### ISSUE TITLE
Enable teachers to update grades

### ISSUE THREAD

**Issue by zsabri91** [zsabri91/Scrum_-_flow#1]
**user story**
_As a teacher, i tend to lose my paper records. So, I want to update the grades online so that the grades will be stored  even if I lose the paper records.

**Tasks** 

- [x] Create modules for grades
- [x] Create API ends points for updating grades
- [x] Create a UI for the teacher to ad new grades

**Acceptance criteria**
* only work on chrome
 * only the teacher will be able to update grades
 *Will not check if the grades are valid or not

**Acceptance tests**
1. A teacher is able to add a new grade for the student
2. A teacher is able to edit an existing grade for a student 
3. a teacher is able to remove an existing grade for a student
4. a teacher is able to the grade of the student

**Comment by zsabri91** [comment]
#1
